language: cpp
dist: bionic

install: 
  # Required on bionic
  - sudo apt update -qq
  # Qt5
  - sudo apt install -qq qt5-qmake qt5-default
  # clang-tidy
  - sudo apt install -qq clang clang-format

script: 
  # Build and run this project
  - qmake
  - make debug --silent
  - ./travis_qmake_gcc_cpp17_clang-format || true
  # clang-format
  # Works OK on main_ok.cpp
  - clang-format main_ok.cpp > tmp.txt ; diff main_ok.cpp tmp.txt --suppress-common-lines -y
  # Fails on main.cpp, use '|| true' to make the build pass
  - clang-format main.cpp > tmp.txt ; diff main.cpp tmp.txt --suppress-common-lines -y || true




